CREATE DATABASE PAISAGEM;

USE PAISAGEM;

CREATE TABLE USUARIOS(
	ID_USUARIO INT PRIMARY KEY NOT NULL,
	NOME VARCHAR (100),
	EMAIL VARCHAR (100),
	MATRICULA VARCHAR (10),
	CARGO VARCHAR (50),
	SENHA VARCHAR (50) NOT NULL,
	SALT VARCHAR (50) NOT NULL
);

CREATE TABLE ESPECIES(
	ID_ESPECIE INT PRIMARY KEY NOT NULL,
	NOME_CIENTIFICO VARCHAR (100),
	NOME_POPULAR VARCHAR (100),
	NATURALIDADE VARCHAR (50),
	PORTE VARCHAR (50),
	GENERO VARCHAR (50),
	POPULACAO VARCHAR (50)	
);

CREATE TABLE FAMILIAS(
	ID_FAMILIA INT PRIMARY KEY NOT NULL,
	NOME VARCHAR(100),
	DESCRICAO VARCHAR(300)
);

CREATE TABLE CLASSIFICACOES(
	ID_CLASSIFICACAO INT PRIMARY KEY NOT NULL,
	NOME VARCHAR(100),
	DESCRICAO VARCHAR(300)
);